[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = false
optimizer_runs = 200

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# Setting up RPC URLs and private keys for networks
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
lisk-sepolia = "${LISK_SEPOLIA_RPC_URL}"
localhost = "${LOCALHOST}"

# Etherscan API key for verification
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# Custom chain for lisk-sepolia
[etherscan]
lisk-sepolia = { chain_id = 4202, api_url = "https://sepolia-blockscout.lisk.com/api", browser_url = "https://sepolia-blockscout.lisk.com/", key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
